# -*- coding: utf-8 -*-
"""CSPC901_Assignment4_RahulBiswas_16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vAs07ORRN6ud6jOzrO_xkzd2CArRH87y
"""

import math
from collections import Counter

def read_dict(filename):
    try:
        words=[]
        with open(filename,encoding ='utf-8') as f:
            for line in f:
                eng, ben = line.strip().split(maxsplit=1)
                words.append(eng)
        return words
    except FileNotFoundError:
        print('File not found')
def read_input(filename):
    try:
        words = []
        with open(filename,encoding ='utf-8') as f:
            text = f.read()
            words.extend(text.split())
        return words
    except FileNotFoundError:
        print('File not found')
def separate_keys(dict_w,input):
    dict_word = []
    non_dict_words = []

    for word in input:
        if word in dict_w:
            dict_word.append(word)
        else:
            non_dict_words.append(word)
    return dict_word,non_dict_words
def calculate_probabilities(dict_words, non_dict_words, keys):
    dict_counter = Counter(dict_words)
    non_dict_counter = Counter(non_dict_words)

    total = len(dict_words) + len(non_dict_words)
    n = len(keys)

    # p[1..n]
    p = [0] * (n + 1)
    for i, key in enumerate(keys, start=1):
        p[i] = dict_counter[key] / total

    # q[0..n] — REAL gap probabilities
    q = [0] * (n + 1)
    for word, count in non_dict_counter.items():
        placed = False
        for i, key in enumerate(keys):
            if word < key:
                q[i] += count / total
                placed = True
                break
        if not placed:
            q[n] += count / total

    return p, q

def assign_gaps(keys, non_dict_words):
    gaps = {i: [] for i in range(len(keys)+1)}
    for w in non_dict_words:
        placed = False
        for i, k in enumerate(keys):
            if w < k:
                gaps[i].append(w)
                placed = True
                break
        if not placed:
            gaps[len(keys)].append(w)
    return gaps

def optimal_bst(p, q, n):
    e = [[0]*(n+1) for _ in range(n+2)]
    w = [[0]*(n+1) for _ in range(n+2)]
    root = [[0]*(n+1) for _ in range(n+1)]

    for i in range(1, n+2):
        e[i][i-1] = q[i-1]
        w[i][i-1] = q[i-1]

    for l in range(1, n+1):
        for i in range(1, n-l+2):
            j = i + l - 1
            e[i][j] = math.inf
            w[i][j] = w[i][j-1] + p[j] + q[j]

            for r in range(i, j+1):
                t = e[i][r-1] + e[r+1][j] + w[i][j]
                if t < e[i][j]:
                    e[i][j] = t
                    root[i][j] = r

    return e, root

def print_obst(root, keys, gaps, i, j, depth=1):
    if i > j:
        gap_words = gaps.get(j, [])
        label = ", ".join(gap_words) if gap_words else "-"
        print("  "*(depth-1) + f"[NON-DICT] {label}")
        return

    r = root[i][j]
    print("  "*(depth-1) + f"{keys[r-1]} (depth={depth}) [DICT]")
    print_obst(root, keys, gaps, i, r-1, depth+1)
    print_obst(root, keys, gaps, r+1, j, depth+1)

class AVLNode:
    def __init__(self, key):
        self.key = key
        self.left = None
        self.right = None
        self.height = 1

def height(n): return n.height if n else 0

def rotate_right(y):
    x = y.left
    T = x.right
    x.right = y
    y.left = T
    y.height = max(height(y.left), height(y.right)) + 1
    x.height = max(height(x.left), height(x.right)) + 1
    return x

def rotate_left(x):
    y = x.right
    T = y.left
    y.left = x
    x.right = T
    x.height = max(height(x.left), height(x.right)) + 1
    y.height = max(height(y.left), height(y.right)) + 1
    return y

def insert_avl(root, key):
    if not root:
        return AVLNode(key)
    if key < root.key:
        root.left = insert_avl(root.left, key)
    else:
        root.right = insert_avl(root.right, key)

    root.height = 1 + max(height(root.left), height(root.right))
    balance = height(root.left) - height(root.right)

    if balance > 1 and key < root.left.key:
        return rotate_right(root)
    if balance < -1 and key > root.right.key:
        return rotate_left(root)
    if balance > 1 and key > root.left.key:
        root.left = rotate_left(root.left)
        return rotate_right(root)
    if balance < -1 and key < root.right.key:
        root.right = rotate_right(root.right)
        return rotate_left(root)

    return root

def avl_cost(node, probs, depth=1):
    if not node:
        return 0
    i = probs["index"][node.key]
    cost = probs["p"][i] * depth
    return cost + avl_cost(node.left, probs, depth+1) + avl_cost(node.right, probs, depth+1)

dict_w = read_dict('dict.txt')
input_words = read_input('input.txt')

dict_words, non_dict_words = separate_keys(dict_w, input_words)

keys = sorted(set(dict_words))
p, q = calculate_probabilities(dict_words, non_dict_words, keys)

e, root = optimal_bst(p, q, len(keys))
gaps = assign_gaps(keys, non_dict_words)

print("\nOptimal BST structure:\n")
print_obst(root, keys, gaps, 1, len(keys))

print("\nExpected search cost:", e[1][len(keys)])


avl = None
for k in keys:
    avl = insert_avl(avl, k)

probs = {"p": p, "index": {k:i+1 for i,k in enumerate(keys)}}
avl_expected_cost = avl_cost(avl, probs)

print("Expected Search Cost (AVL Tree):", round(avl_expected_cost, 4))